# Generated by Django 2.0 on 2018-01-11 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customize_auth', '0002_auto_20180108_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回答内容')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False, verbose_name='禁用')),
                ('approvals', models.ManyToManyField(related_name='approval_answer', to='customize_auth.User')),
                ('negations', models.ManyToManyField(related_name='negation_answer', to='customize_auth.User')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True, verbose_name='提问标题')),
                ('description', models.TextField(verbose_name='提问描述')),
                ('type', models.CharField(max_length=40, verbose_name='问题类型')),
                ('solved', models.BooleanField(default=False, verbose_name='解决状态')),
                ('disabled', models.BooleanField(default=False, verbose_name='禁用')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('best_answer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acception_as_best', to='qa.Answer')),
                ('first_answer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acception_as_first', to='qa.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='customize_auth.User')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qa.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='customize_auth.User'),
        ),
    ]
